### PR TITLE
Proposed solution for ASSIST-41

### PR DESCRIPTION
**Pull request by olemp**
Implemented fix mentioned here: http://stackoverflow.com/questions/29659969/cannot-filter-a-sharepoint-2013-task-list-after-march-2015-update

See ASSIST-41 for details.

### CODE REVIEW

**Comment by okms** [comment]
Will merge and test locally before including in the main branch

**Comment by tarjeieo** [comment]
And just a quick note that it's better to explain the actual issue than to refer to an issue number outside anyone's reach but ours.

**Comment by okms** [comment]
View query had to be changed, yes

**Comment by okms** [comment]
Fix confirmed as working. Thank you @olemp. Merging into master and releasing

**Pull request merged**
